Cargo.toml, LICENSE, README.md
Related https://github.com/stratis-storage/project/issues/677
=> Adjust packaging

Cargo.toml
Related https://github.com/stratis-storage/project/issues/677
=> Specify some ignores for packaging crate

.github/workflows/ci.yml, .gitignore, CHANGES.txt, Cargo.toml, Makefile
Related https://github.com/stratis-storage/project/issues/693
=> version 0.5.1

.github/workflows/ci.yml
Related: stratis-storage/project#695
=> github actions: update FEDORA_RELEASE to F40, F39

.github/workflows/ci.yml
Related: stratis-storage/project#700
=> github actions: update recommended Rust to 1.77.2

Cargo.toml, tests/util/mod.rs
Related https://github.com/stratis-storage/project/issues/698
=> Use once_cell instead of lazy_static for lazy statics

.github/workflows/ci.yml
Related: stratis-storage/project#706
=> Advance current development environment to Fedora 40

.github/workflows/ci.yml
Related: stratis-storage/project#712
=> github actions: update recommended Rust to 1.79.0

Cargo.toml, Makefile
Related https://github.com/stratis-storage/project/issues/721
=> Use Cargo.toml to specify lint policy

.github/workflows/ci.yml
Related: stratis-storage/project#720
=> github actions: update recommended Rust to 1.80.0

.github/workflows/ci.yml
Related: stratis-storage/project#727
=> github actions: update recommended Rust to 1.81.0

.github/workflows/ci.yml, Makefile
=> Add standardized Makefile targets

.github/workflows/ci.yml
Related: stratis-storage/project#733
=> github actions: update recommended Rust to 1.82.0

.github/workflows/ci.yml
Related: stratis-storage/project#739
=> github actions: update FEDORA_RELEASE to F41, F40

Cargo.toml
https://github.com/stratis-storage/project/issues/743
=> Cargo.toml: Set rust-version to 1.74.0

.github/workflows/ci.yml
Related: stratis-storage/project#747
=> github actions: update recommended Rust to 1.84.0

.github/workflows/ci.yml, .github/workflows/dummy.yml
Related https://github.com/stratis-storage/project/issues/752
=> Use Ubuntu 22.04 image

.github/workflows/ci.yml
Related: stratis-storage/project#751
=> github actions: update recommended Rust to 1.84.1

.github/workflows/ci.yml
Related: stratis-storage/project#753
=> github actions: update recommended Rust to 1.85

.github/workflows/ci.yml
Related: https://github.com/stratis-storage/project/issues/763
=> github actions: update recommended Rust to 1.86

.github/workflows/ci.yml
Related: stratis-storage/project#739
=> Advance current development environment to Fedora 41

.github/workflows/ci.yml, .github/workflows/nightly.yml
Related https://github.com/stratis-storage/project/issues/768
=> Drop f40 from Fedora version comparisons

Cargo.toml
Related https://github.com/stratis-storage/project/issues/773
=> Allow default features for bindgen dependency

.github/workflows/ci.yml, .github/workflows/nightly.yml
Related https://github.com/stratis-storage/project/issues/779
=> github actions: Update recommended Rust to 1.87.0

src/lib.rs, tests/integration_test.rs
Related https://github.com/stratis-storage/project/issues/786
=> clippy 1.88.0 fixes

.github/workflows/ci.yml, .github/workflows/nightly.yml
Related https://github.com/stratis-storage/project/issues/795
=> github actions: Update recommended Rust to 1.89.0
